const MAP_URL = "https://maps.app.goo.gl/AM7NTFfv98BUCmkb8?g_st=ic";
const TIMES = ["9:00 AM", "9:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "1:00 PM", "1:30 PM", "2:00 PM", "2:30 PM"];
const DOCS = ["Identificación oficial", "Número de IMSS", "CURP", "RFC", "Acta de nacimiento", "Último comprobante de estudios", "Comprobante de domicilio actual"];
const cfg = window.PMW_CONFIG || {};
const configured = cfg.SUPABASE_URL && !cfg.SUPABASE_URL.includes("PASTE_") && cfg.SUPABASE_ANON_KEY && !cfg.SUPABASE_ANON_KEY.includes("PASTE_");
const db = configured ? window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY) : null;

const state = { step:1, inMexicali:null, role:"", name:"", phone:"", date:"", time:"", taken:new Set() };
const app = document.getElementById("app");
const progressBar = document.getElementById("progressBar");

function setProgress(){ const widths={1:14,2:28,3:43,4:57,5:72,6:86,7:100}; progressBar.style.width=`${widths[state.step]||14}%`; }
function esc(v=""){ return v.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"}[c])); }
function render(){ setProgress(); const views={1:renderLocation,2:renderRole,3:renderDetails,4:renderDate,5:renderTime,6:renderReview,7:renderSuccess}; app.innerHTML=views[state.step](); wireEvents(); window.scrollTo({top:0,behavior:"smooth"}); }
function renderLocation(){ return `<span class="step-tag">Paso 1 de 6</span><h1>Agenda tu entrevista</h1><p class="subtitle">Primero necesitamos confirmar que puedes acudir presencialmente.</p>${!configured?'<div class="notice">Modo de vista previa: falta conectar Supabase para reservar desde distintos celulares.</div>':''}<div class="option-grid"><button class="option-btn" data-action="mexicali-yes">Sí, estoy en Mexicali</button><button class="option-btn danger" data-action="mexicali-no">No estoy en Mexicali</button></div>`; }
function renderRole(){ return `<span class="step-tag">Paso 2 de 6</span><h1>¿A qué puesto deseas aplicar?</h1><p class="subtitle">Selecciona una vacante para continuar.</p><div class="option-grid">${["Soldador","Armador","Labores generales"].map(r=>`<button class="option-btn" data-role="${r}">${r}</button>`).join("")}</div><div class="actions"><button class="secondary-btn" data-back>Regresar</button></div>`; }
function renderDetails(){ return `<span class="step-tag">Paso 3 de 6</span><h1>Cuéntanos sobre ti</h1><p class="subtitle">Usaremos estos datos únicamente para identificar tu entrevista.</p><form id="detailsForm" class="form-grid" novalidate><label>Nombre completo<input id="name" type="text" autocomplete="name" placeholder="Ej. Juan Pérez López" value="${esc(state.name)}" required></label><label>Número de teléfono<input id="phone" type="tel" inputmode="tel" autocomplete="tel" placeholder="Ej. 686 123 4567" value="${esc(state.phone)}" required><span class="help">Incluye lada. No compartiremos tu número.</span></label><div id="formError" class="error" hidden></div><div class="actions"><button type="button" class="secondary-btn" data-back>Regresar</button><button type="submit" class="primary-btn">Continuar</button></div></form>`; }
function nextBusinessDays(count=20){ const out=[]; const d=new Date(); d.setHours(12,0,0,0); d.setDate(d.getDate()+1); while(out.length<count){ if(d.getDay()!==0&&d.getDay()!==6) out.push(new Date(d)); d.setDate(d.getDate()+1); } return out; }
function dateKey(d){ return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`; }
function formatDate(key,long=true){ const [y,m,d]=key.split("-").map(Number); const dt=new Date(y,m-1,d,12); return new Intl.DateTimeFormat("es-MX",long?{weekday:"long",day:"numeric",month:"long",year:"numeric"}:{weekday:"short",day:"numeric",month:"short"}).format(dt); }
function renderDate(){ return `<span class="step-tag">Paso 4 de 6</span><h1>Selecciona el día</h1><p class="subtitle">Las entrevistas están disponibles de lunes a viernes.</p><div class="date-grid">${nextBusinessDays().map(d=>{const k=dateKey(d);return `<button class="date-btn" data-date="${k}"><strong>${formatDate(k,false)}</strong><span>Ver horarios</span></button>`}).join("")}</div><div class="actions"><button class="secondary-btn" data-back>Regresar</button></div>`; }
async function loadTaken(){ state.taken=new Set(); if(!db) return; const {data,error}=await db.rpc("get_booked_slots",{p_date:state.date}); if(error) throw error; (data||[]).forEach(r=>state.taken.add(r.time_slot)); }
function renderTime(){ return `<span class="step-tag">Paso 5 de 6</span><h1>Selecciona un horario</h1><p class="subtitle">${formatDate(state.date)} · Cada entrevista dura 30 minutos.</p><div class="slot-grid">${TIMES.map(t=>`<button class="slot-btn" data-time="${t}" ${state.taken.has(t)?"disabled":""}>${t}</button>`).join("")}</div><div class="actions"><button class="secondary-btn" data-back>Regresar</button></div>`; }
function renderReview(){ return `<span class="step-tag">Paso 6 de 6</span><h1>Revisa tu entrevista</h1><p class="subtitle">Confirma que la información sea correcta antes de agendar.</p><div class="summary-box"><div class="summary-row"><span>Nombre</span><strong>${esc(state.name)}</strong></div><div class="summary-row"><span>Teléfono</span><strong>${esc(state.phone)}</strong></div><div class="summary-row"><span>Puesto</span><strong>${esc(state.role)}</strong></div><div class="summary-row"><span>Fecha</span><strong>${formatDate(state.date)}</strong></div><div class="summary-row"><span>Hora</span><strong>${state.time}</strong></div></div><div class="notice">Al confirmar, este horario quedará reservado.</div><div id="bookingError" class="error" hidden></div><div class="actions"><button class="secondary-btn" data-back>Regresar</button><button class="primary-btn" data-action="confirm">Confirmar entrevista</button></div>`; }
function renderSuccess(){ return `<div class="success-icon">✓</div><span class="step-tag">Confirmada</span><h1>¡Tu entrevista ha sido agendada!</h1><p class="subtitle">Guarda esta información y llega 10 minutos antes.</p><div class="summary-box"><div class="summary-row"><span>Nombre</span><strong>${esc(state.name)}</strong></div><div class="summary-row"><span>Puesto</span><strong>${esc(state.role)}</strong></div><div class="summary-row"><span>Fecha</span><strong>${formatDate(state.date)}</strong></div><div class="summary-row"><span>Hora</span><strong>${state.time}</strong></div></div><div class="docs-box"><h3>Documentación para nuevo ingreso</h3><ul>${DOCS.map(d=>`<li>${d}</li>`).join("")}</ul></div><div class="location-box"><h3>Ubicación de la entrevista</h3><p>Precision Metal Works, Mexicali.</p><a class="map-btn" href="${MAP_URL}" target="_blank" rel="noopener">Abrir ubicación en Maps</a></div><div class="actions"><button class="secondary-btn" data-action="new">Agendar otra entrevista</button></div>`; }
function go(step){ state.step=step; render(); }
function showFatal(msg){ app.innerHTML=`<h1>No se pudo continuar</h1><div class="error">${esc(msg)}</div><div class="actions"><button class="secondary-btn" onclick="location.reload()">Intentar de nuevo</button></div>`; }
function wireEvents(){
  app.querySelector('[data-action="mexicali-yes"]')?.addEventListener("click",()=>{state.inMexicali=true;go(2)});
  app.querySelector('[data-action="mexicali-no"]')?.addEventListener("click",()=>{app.innerHTML=`<span class="step-tag">Entrevistas presenciales</span><h1>Por el momento solo atendemos en Mexicali</h1><p class="subtitle">Necesitas poder acudir presencialmente a Precision Metal Works para continuar.</p><div class="actions"><button class="secondary-btn" id="restart">Regresar</button></div>`;document.getElementById("restart").onclick=()=>go(1)});
  app.querySelectorAll("[data-role]").forEach(b=>b.addEventListener("click",()=>{state.role=b.dataset.role;go(3)}));
  app.querySelectorAll("[data-date]").forEach(b=>b.addEventListener("click",async()=>{state.date=b.dataset.date;state.time="";app.innerHTML='<p class="subtitle">Cargando horarios disponibles…</p>';try{await loadTaken();go(5)}catch(e){showFatal("No pudimos cargar los horarios. Intenta de nuevo.")}}));
  app.querySelectorAll("[data-time]").forEach(b=>b.addEventListener("click",()=>{state.time=b.dataset.time;go(6)}));
  app.querySelectorAll("[data-back]").forEach(b=>b.addEventListener("click",()=>go(Math.max(1,state.step-1))));
  document.getElementById("detailsForm")?.addEventListener("submit",e=>{e.preventDefault();const name=document.getElementById("name").value.trim();const phone=document.getElementById("phone").value.trim();const err=document.getElementById("formError");if(name.split(/\s+/).length<2){err.hidden=false;err.textContent="Escribe tu nombre y al menos un apellido.";return}if(phone.replace(/\D/g,"").length<10){err.hidden=false;err.textContent="Escribe un número de teléfono válido de 10 dígitos.";return}state.name=name;state.phone=phone;go(4)});
  app.querySelector('[data-action="confirm"]')?.addEventListener("click",async()=>{const btn=app.querySelector('[data-action="confirm"]');const err=document.getElementById("bookingError");if(!db){err.hidden=false;err.textContent="La página todavía está en modo de vista previa. Falta conectarla a Supabase para publicar reservas reales.";return}btn.disabled=true;btn.textContent="Confirmando…";const {error}=await db.from("interviews").insert({full_name:state.name,phone:state.phone,role:state.role,interview_date:state.date,time_slot:state.time});if(error){btn.disabled=false;btn.textContent="Confirmar entrevista";err.hidden=false;err.textContent=error.code==="23505"?"Ese horario acaba de ocuparse. Regresa y elige otro.":"No pudimos guardar la entrevista. Intenta de nuevo.";return}go(7)});
  app.querySelector('[data-action="new"]')?.addEventListener("click",()=>{Object.assign(state,{step:1,inMexicali:null,role:"",name:"",phone:"",date:"",time:"",taken:new Set()});render()});
}
render();
